<div style="background-color: #ffffff; padding: 28px 30px; border-radius: 10px; border: 1px solid #e5d0d2; font-family: 'Segoe UI', sans-serif;">

  <h1 style="color: #722F37; text-align: center; font-size: 24px; font-weight: 800; margin-bottom: 12px; border-bottom: 3px solid #722F37; padding-bottom: 10px;">
    Projeto 1: Pré-Processamento e Análise Exploratória de Dados
  </h1>

  <p style="color: #555; text-align: center; font-size: 14px; line-height: 1.5; margin-bottom: 25px;">
    Análise integradora dos dados abertos de acidentes e infrações da Polícia Rodoviária Federal (PRF) entre os anos de 2024 e 2025.
  </p>

  <div style="font-size: 13px; color: #333; line-height: 2;">
    <div><strong style="color: #722F37;">Disciplina:</strong> Estatística Aplicada</div>
    <div><strong style="color: #722F37;">Professor:</strong> Paulo Ribeiro</div>
    <div><strong style="color: #722F37;">Aluno:</strong> Gabriel Felipe Da Silva Sampaio</div>
    <div><strong style="color: #722F37;">Conjuntos Selecionados:</strong> Acidentes (pessoas) e multas dos anos 2024 e 2025.</div>
  </div>

</div>

In [4]:
import pandas as pd
import os

In [5]:
acidentes_2024 = pd.read_csv('dados_acidentes/acidentes2024.csv', sep = ';', encoding = 'latin1')
acidentes_2025 = pd.read_csv('dados_acidentes/acidentes2025.csv', sep = ';', encoding = 'latin1')
print(f'Variavbeis de 2024: {acidentes_2024.columns.tolist()}\n')
print(f'Variaveis de 2025: {acidentes_2025.columns.tolist()}\n')

Variavbeis de 2024: ['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca', 'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade', 'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

Variaveis de 2025: ['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca', 'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade', 'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

In [6]:
colunas_2024 = set(acidentes_2024.columns)
colunas_2025 = set(acidentes_2025.columns)
print(f'Colunas exclusivas a 2024: {sorted(colunas_2024 - colunas_2025)}')
print(f'\nColunas exclusivas a 2025 {sorted(colunas_2025 - colunas_2024)}')
print(f'\nQuantidade de colunas em comum: {len(colunas_2024 & colunas_2025)}')
if len(colunas_2024 & colunas_2025) == 35:
    print('AS colunas estao padronizadas nesses anos, nao será necessario qualquer mudança')
else:
    print(f'{35 - len(colunas_2024 & colunas_2025)} colunas estao alteradas')

Colunas exclusivas a 2024: []

Colunas exclusivas a 2025 []

Quantidade de colunas em comum: 35
AS colunas estao padronizadas nesses anos, nao será necessario qualquer mudança

### 1.1 Comparação das variáveis — Dados de acidentes

Inicialmente, foram carregados os conjuntos de dados de acidentes referentes aos anos de 2024 e 2025. Em seguida, as listas de variáveis presentes em cada conjunto foram comparadas computacionalmente.

A comparação demonstrou que **não existem variáveis presentes exclusivamente em um dos anos**. Dessa forma, os conjuntos de dados de acidentes de 2024 e 2025 apresentam a **mesma estrutura de variáveis**, permitindo a combinação dos dados posteriormente.

In [7]:
# Importando nova biblioteca para manuseio de caminhos e leitura mais fluida
import glob 
arquivo_multas_2024 = sorted(glob.glob('dados_multas/ajustados_2024/*csv'))
arquivo_multas_2025 = sorted(glob.glob(('dados_multas/ajustados_2025/*csv')))

print(f'Arquivos de multas de 2024: {len(arquivo_multas_2024)}')
print(f'Arquivos de multas de 2025: {len(arquivo_multas_2025)}')

for arquivo in arquivo_multas_2024:
    print(arquivo)

print(f'\n\n')

for arquivo in arquivo_multas_2025:
    print(arquivo)

Arquivos de multas de 2024: 12
Arquivos de multas de 2025: 12
dados_multas/ajustados_2024\infraçoes2024_01.csv
dados_multas/ajustados_2024\infraçoes2024_02.csv
dados_multas/ajustados_2024\infraçoes2024_03.csv
dados_multas/ajustados_2024\infraçoes2024_04.csv
dados_multas/ajustados_2024\infraçoes2024_05.csv
dados_multas/ajustados_2024\infraçoes2024_07.csv
dados_multas/ajustados_2024\infraçoes2024_08.csv
dados_multas/ajustados_2024\infraçoes2024_09.csv
dados_multas/ajustados_2024\infraçoes2024_10.csv
dados_multas/ajustados_2024\infraçoes2024_11.csv
dados_multas/ajustados_2024\infraçoes2024_12a.csv
dados_multas/ajustados_2024\infraçoes2024_12b.csv



dados_multas/ajustados_2025\infraçoes2025_01.csv
dados_multas/ajustados_2025\infraçoes2025_02.csv
dados_multas/ajustados_2025\infraçoes2025_03.csv
dados_multas/ajustados_2025\infraçoes2025_04.csv
dados_multas/ajustados_2025\infraçoes2025_05.csv
dados_multas/ajustados_2025\infraçoes2025_06.csv
dados_multas/ajustados_2025\infraçoes2025_07.csv
dados_multas/ajustados_2025\infraçoes2025_08.csv
dados_multas/ajustados_2025\infraçoes2025_09.csv
dados_multas/ajustados_2025\infraçoes2025_10.csv
dados_multas/ajustados_2025\infraçoes2025_11.csv
dados_multas/ajustados_2025\infraçoes2025_12.csv

### Observação sobre os arquivos de multas de 2024 / póssivel mistério no ar

Durante a verificação dos arquivos disponibilizados para o ano de 2024, foi identificada uma particularidade na organização dos dados.

Foram encontrados 12 arquivos na pasta `ajustados_2024`, porém a sequência mensal apresenta a ausência do arquivo referente ao mês de junho (`infrações2024_06.csv`). Em contrapartida, o mês de dezembro encontra-se dividido em dois arquivos:

* `infrações2024_12a.csv`
* `infrações2024_12b.csv`

Dessa forma, essa característica foi registrada durante a etapa de conferência dos dados e será considerada nas etapas posteriores de combinação e análise. Não será presumida a existência de dados para junho enquanto essa situação não for devidamente verificada.

In [8]:
# Iterações para testar colunas (uso da ram em 94%)
for arquivo in arquivo_multas_2024:
    df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

    print(
        f'{arquivo.split(chr(92))[-1]} ->'
        f'{df_auxilio.shape[0]} linha / '
        f'{df_auxilio.shape[1]} colunas'

        )

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_01.csv ->632663 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_02.csv ->564176 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_03.csv ->653288 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_04.csv ->649949 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_05.csv ->639541 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_07.csv ->836554 linha / 25 colunas
infraçoes2024_08.csv ->915981 linha / 25 colunas
infraçoes2024_09.csv ->957494 linha / 25 colunas
infraçoes2024_10.csv ->898349 linha / 25 colunas
infraçoes2024_11.csv ->902342 linha / 25 colunas
infraçoes2024_12a.csv ->448366 linha / 25 colunas

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3346794345.py:3: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding= 'latin1')

infraçoes2024_12b.csv ->611319 linha / 25 colunas

### Verificação preliminar dos arquivos de multas de 2024

A leitura preliminar dos arquivos de multas de 2024 mostrou que todos os arquivos analisados possuem **25 colunas**, porém apresentam diferentes quantidades de registros.

Também foram identificados avisos (`DtypeWarning`) durante a leitura de alguns arquivos. Esses avisos indicam que determinadas colunas apresentam **tipos de dados mistos**, ou seja, existem valores que foram interpretados como tipos diferentes dentro da mesma coluna, duas colunas **(22 e 23)** estao causando os maiores ploblemas.

Visando otimização de memoria e organização de ideias, essa parte será tratada mais tarde, também está em pauta o mês sumido, caracteristica será registrada para verificação posterior

In [9]:
# Tentando localizar as colunas problematicas
for i, coluna in enumerate(df_auxilio.columns):
    print(i, coluna)

0 Número do Auto
1 Data da Infração (DD/MM/AAAA)
2 Indicador de Abordagem
3 Assinatura do Auto
4 Sentido Trafego
5 UF Infração
6 BR Infração
7 Km Infração
8 Município
9 Indicador Veiculo Estrangeiro
10 UF Placa
11 Descrição Especie Veículo
12 Descrição Marca Veículo
13 Descrição Tipo Veículo
14 Descrição Modelo Veiculo
15 Código da Infração
16 Descrição Abreviada Infração
17 Enquadramento da Infração
18 Início Vigência da Infração
19 Fim Vigência Infração
20 Medição Infração
21 Hora Infração
22 Medição Considerada
23 Excesso Verificado
24 Qtd Infrações

### Tipos de dados identificados preliminarmente

Durante a leitura dos arquivos de multas de 2024, foram identificados avisos de tipos de dados mistos (`DtypeWarning`) em algumas colunas.

Nos arquivos analisados, as colunas associadas aos avisos foram:

* **Código da Infração** — índice 15;
* **Medição Considerada** — índice 22;
* **Excesso Verificado** — índice 23.

Por enquanto nada será mudado, os dados continuaram de forma original, até (esperado) a etapa de limpeza, a presença de tipos mistos indicam que as variaveis terão que ser analisadas com calma.

In [10]:
# os nomes propriamentes ditos terão que ser analisados, não existe garantia que as 25 são as mesmas, uma redundancia para comparação
colunas_multas_24 = {}
for arquivo in arquivo_multas_2024:
    df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')

    nome_arquivo = arquivo.split('\\')[-1]
    colunas_multas_24[nome_arquivo] = df_auxilio01.columns.tolist()

for arquivo, colunas in colunas_multas_24.items():
    print(f'{arquivo}: {len(colunas)} colunas')

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\3228382742.py:4: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio01 = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')

infraçoes2024_01.csv: 25 colunas
infraçoes2024_02.csv: 25 colunas
infraçoes2024_03.csv: 25 colunas
infraçoes2024_04.csv: 25 colunas
infraçoes2024_05.csv: 25 colunas
infraçoes2024_07.csv: 25 colunas
infraçoes2024_08.csv: 25 colunas
infraçoes2024_09.csv: 25 colunas
infraçoes2024_10.csv: 25 colunas
infraçoes2024_11.csv: 25 colunas
infraçoes2024_12a.csv: 25 colunas
infraçoes2024_12b.csv: 25 colunas

In [11]:
colunas_based = None

for arquivo in arquivo_multas_2024:
    df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')

    col_atual = df_auxilio.columns.tolist()

    if colunas_based is None:
        colunas_based = col_atual
        #arquivo_based = arquivo #por enquanto
    else:
        if col_atual != colunas_based:
            print(f'Diferença encontrada em: {arquivo}')
print('Todas as verificações foram feitas')

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\2146262378.py:4: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')

Todas as verificações foram feitas

### Em meio a tantas gigas tivemos a primeira notícia boa, as variaveis são as mesmas em todo o ano de 2024

In [12]:
# Testando o mesmo codigo da ultima celula com 2025
colunas_based = None

for arquivo in arquivo_multas_2025:
    df_auxilio = pd.read_csv(arquivo, sep = ';', encoding='latin1')

    col_atual = df_auxilio.columns.tolist() #isso aqui itera junto

    if colunas_based is None:
        colunas_based = col_atual
        #arquivo_based = arquivo
    else:
        if col_atual != colunas_based:
            print(f'Diferença encontrada em: {arquivo}')
print('Verificações para 2025 foram feitas')

Verificações para 2025 foram feitas

In [13]:
colunas_2024 = set(colunas_based)

df_2025 = pd.read_csv(arquivo_multas_2025[0], sep = ';', encoding= 'latin1')

colunas_2025 = set(df_2025.columns)

print(f'Colunas presentes somente em 2024\n {sorted(colunas_2024 - colunas_2025)}\n')

print(f'\nColunas presentes somente em 2025\n {sorted(colunas_2025 - colunas_2024)}')

print(f'\nColunas presentes nos dois anos: \n {sorted(colunas_2024 & colunas_2025)}')

Colunas presentes somente em 2024
 []


Colunas presentes somente em 2025
 []

Colunas presentes nos dois anos:
 ['Assinatura do Auto', 'BR Infração', 'Código da Infração', 'Data da Infração (DD/MM/AAAA)', 'Descrição Abreviada Infração', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Descrição Modelo Veiculo', 'Descrição Tipo Veículo', 'Enquadramento da Infração', 'Excesso Verificado', 'Fim Vigência Infração', 'Hora Infração', 'Indicador Veiculo Estrangeiro', 'Indicador de Abordagem', 'Início Vigência da Infração', 'Km Infração', 'Medição Considerada', 'Medição Infração', 'Município', 'Número do Auto', 'Qtd Infrações', 'Sentido Trafego', 'UF Infração', 'UF Placa']

### 1.2 Comparação das variaveis -- Dados de multas

Após a verificação individual dos arquivos de multas de 2024 e 2025, foi realizada a comparação entre as variaveis dos dois anos

Foi demonstrado que ***não existem variaveis exclusivas***, o que nos garante mesma estrutura de colunas/variaveis, e além de tudo isso foi identificado ***25 colunas comuns a ambos***.

### 1.3 Comparação entre as variáveis dos conjuntos de acidentes e multas

Após a verificação das estruturas dos conjuntos de dados de acidentes e multas, foi realizada uma comparação semântica entre suas variáveis, utilizando os respectivos dicionários de dados.

A análise demonstrou que algumas variáveis apresentam **significados equivalentes, apesar de possuírem nomes diferentes**. Entre elas estão informações relacionadas à data, localização da ocorrência, sentido do tráfego e características dos veículos.

As principais correspondências identificadas foram:

* `data_inversa` ↔ `dat_infracao`: data da ocorrência ou infração;
* `uf` ↔ `uf_infracao`: Unidade Federativa do local;
* `br` ↔ `num_br_infracao`: identificação da BR;
* `km` ↔ `num_km_infracao`: quilômetro da ocorrência;
* `municipio` ↔ `nom_municipio`: município;
* `sentido_via` ↔ `ind_sentido_trafego`: sentido do tráfego;
* `tipo_veiculo` ↔ `Descrição Tipo Veículo`: tipo do veículo;
* `marca` ↔ `Descrição Marca Veículo`: marca do veículo.

Apesar dessas correspondências, os conjuntos não possuem as mesmas variáveis em sua totalidade. O conjunto de acidentes contém informações específicas sobre o acidente e sobre as pessoas envolvidas, como causa, tipo e classificação do acidente, fase do dia, estado físico, idade e sexo. Já o conjunto de multas possui informações específicas relacionadas à infração, como abordagem, assinatura do auto, enquadramento, vigência da infração e medições realizadas.

Portanto, os conjuntos apresentam **algumas variáveis semanticamente relacionadas, mas possuem estruturas e finalidades distintas**, não sendo possível considerar que todas as variáveis de um conjunto possuem correspondentes no outro. (por lógica relacionalos não faz muito sentido, tomaremos isso por convenção)

In [14]:
# Vamos criar um único DataFrame com os dois anos
acidentes = pd.concat([acidentes_2024, acidentes_2025], keys = [2024, 2025], names = ['ano'])
print(f'Total registros = {len(acidentes)}')
print(f'Quantidade de variaveis = {acidentes.shape[1]}\n\n')
acidentes.head()

Total registros = 390935
Quantidade de variaveis = 35

              id    pesid data_inversa     dia_semana   horario  uf   br   km  \
ano
2024 0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38
     1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185
     2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578
     3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18
     4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240

                 municipio                                     causa_acidente  \
ano
2024 0  CONCEICAO DA BARRA                             Ultrapassagem Indevida
     1            PIRIPIRI                        Manobra de mudança de faixa
     2             BREJOES                   Ingestão de álcool pelo condutor
     3    MALHADA DOS BOIS           Reação tardia ou ineficiente do condutor
     4        RONDONOPOLIS  Condutor deixou de manter distância do veículo...

        ...       sexo ilesos feridos_leves feridos_graves mortos   latitude  \
ano     ...
2024 0  ...  Masculino      1             0              0      0  -18.48261
     1  ...  Masculino      1             0              0      0  -4.296033
     2  ...  Masculino      1             0              0      0 -13.071583
     3  ...  Masculino      0             0              1      0 -10.356019
     4  ...  Masculino      1             0              0      0 -16.179141

        longitude regional  delegacia             uop
ano
2024 0  -39.92379  SPRF-ES   DEL04-ES  UOP02-DEL04-ES
     1 -41.767327  SPRF-PI   DEL02-PI  UOP01-DEL02-PI
     2 -39.961111  SPRF-BA   DEL03-BA  UOP02-DEL03-BA
     3 -36.905522  SPRF-SE   DEL02-SE  UOP02-DEL02-SE
     4 -54.789053  SPRF-MT   DEL02-MT  UOP01-DEL02-MT

[5 rows x 35 columns]

In [15]:
#so para garantir
print(acidentes.index.names)
print(acidentes.index.get_level_values('ano').unique())

['ano', None]
Index([2024, 2025], dtype='int64', name='ano')

In [16]:
# agora vai 
multa_2024_lista = []

for arquivo in arquivo_multas_2024:
    df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')

    multa_2024_lista.append(df_auxilio)

multas_2024 = pd.concat(multa_2024_lista, ignore_index= True)

print(f'Total de registros multas em 2024: {len(multas_2024)}')
print(f'Quantidade de variaveis: {multas_2024.shape[1]}')

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\1794272093.py:5: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_auxilio = pd.read_csv(arquivo, sep = ';', encoding = 'latin1')

Total de registros multas em 2024: 8710022
Quantidade de variaveis: 25

In [17]:
multas_2024.head()

,Número do Auto,Data da Infração (DD/MM/AAAA),Indicador de Abordagem,Assinatura do Auto,Sentido Trafego,UF Infração,BR Infração,Km Infração,Município,Indicador Veiculo Estrangeiro,...,Código da Infração,Descrição Abreviada Infração,Enquadramento da Infração,Início Vigência da Infração,Fim Vigência Infração,Medição Infração,Hora Infração,Medição Considerada,Excesso Verificado,Qtd Infrações
0,b41eeb6ba2b32f8,2024-01-30,C,N,C,MG,365,685,MONTE ALEGRE DE MINAS,N,...,66450,Conduzir o veículo com equip obrigatório em de...,230 X,2016-11-01,NaN,Nenhuma,17,0,0,1.0
1,03555be7021b77f,2024-01-19,C,N,D,SC,101,2,ARARANGUA,N,...,50100,Dirigir veículo sem possuir CNH/PPD/ACC,162 I,2016-11-01,NaN,Nenhuma,14,0,0,1.0
2,5c7538ca57dbfb5,2024-01-19,C,N,D,SC,101,2,ARARANGUA,N,...,75790,"Rec sub test,ex clin, peric ou proc q perm cer...",165-A,2016-11-01,NaN,Nenhuma,14,0,0,1.0
3,c5ebbd79f9420c6,2024-01-05,C,S,C,SP,153,171,GUAICARA,N,...,66371,Conduzir o veículo sem equipamento obrigatório,230 IX,2016-11-01,NaN,Nenhuma,18,0,0,1.0
4,48d1d18550ec986,2024-01-29,C,N,D,PA,10,19,DOM ELISEU,N,...,65992,Conduzir o veículo registrado que não esteja d...,230 * V,2016-11-01,NaN,Nenhuma,16,0,0,1.0

In [18]:

del df_auxilio
del multa_2024_lista
multas_2025_lista = []

for arquivo in arquivo_multas_2025:
    df_auxilio = pd.read_csv(
        arquivo,
        sep=';',
        encoding='latin1'
    )
    
    multas_2025_lista.append(df_auxilio)

multas_2025 = pd.concat(multas_2025_lista, ignore_index=True)

print(f'Total de registros de multas em 2025: {len(multas_2025)}')
print(f'Quantidade de variáveis: {multas_2025.shape[1]}')

Total de registros de multas em 2025: 10204474
Quantidade de variáveis: 25

In [20]:
multas_2024.to_csv(
    'multas_2024_combinadas.csv',
    index=False,
    sep=';',
    encoding='latin1'
)

print('Multas de 2024 salvas com sucesso.')

Multas de 2024 salvas com sucesso.

In [21]:
multas_2025.to_csv(
    'multas_2025_combinadas.csv',
    index=False,
    sep=';',
    encoding='latin1'
)

print('Multas de 2025 salvas com sucesso.')

Multas de 2025 salvas com sucesso.

In [22]:


for arquivo in ['multas_2024_combinadas.csv', 'multas_2025_combinadas.csv']:
    tamanho_gb = os.path.getsize(arquivo) / (1024**3)
    print(f'{arquivo}: {tamanho_gb:.2f} GB')

multas_2024_combinadas.csv: 1.84 GB
multas_2025_combinadas.csv: 2.10 GB

In [23]:
del multas_2025
del multas_2024
print('Deletadas')

Deletadas

In [24]:
multas_2024_teste = pd.read_csv(
    'multas_2024_combinadas.csv',
    sep=';',
    encoding='latin1',
    nrows=10000
)

multas_2025_teste = pd.read_csv(
    'multas_2025_combinadas.csv',
    sep=';',
    encoding='latin1',
    nrows=10000
)

multas_teste = pd.concat(
    [multas_2024_teste, multas_2025_teste],
    keys=[2024, 2025],
    names=['Ano']
)

multas_teste.head()

         Número do Auto Data da Infração (DD/MM/AAAA) Indicador de Abordagem  \
Ano
2024 0  b41eeb6ba2b32f8                    2024-01-30                      C
     1  03555be7021b77f                    2024-01-19                      C
     2  5c7538ca57dbfb5                    2024-01-19                      C
     3  c5ebbd79f9420c6                    2024-01-05                      C
     4  48d1d18550ec986                    2024-01-29                      C

       Assinatura do Auto Sentido Trafego UF Infração  BR Infração  \
Ano
2024 0                  N               C          MG          365
     1                  N               D          SC          101
     2                  N               D          SC          101
     3                  S               C          SP          153
     4                  N               D          PA           10

        Km Infração              Município Indicador Veiculo Estrangeiro  ...  \
Ano                                                                       ...
2024 0          685  MONTE ALEGRE DE MINAS                             N  ...
     1            2              ARARANGUA                             N  ...
     2            2              ARARANGUA                             N  ...
     3          171               GUAICARA                             N  ...
     4           19             DOM ELISEU                             N  ...

       Código da Infração                       Descrição Abreviada Infração  \
Ano
2024 0              66450  Conduzir o veículo com equip obrigatório em de...
     1              50100            Dirigir veículo sem possuir CNH/PPD/ACC
     2              75790  Rec sub test,ex clin, peric ou proc q perm cer...
     3              66371     Conduzir o veículo sem equipamento obrigatório
     4              65992  Conduzir o veículo registrado que não esteja d...

       Enquadramento da Infração Início Vigência da Infração  \
Ano
2024 0                     230 X                  2016-11-01
     1                     162 I                  2016-11-01
     2                     165-A                  2016-11-01
     3                    230 IX                  2016-11-01
     4                   230 * V                  2016-11-01

       Fim Vigência Infração  Medição Infração Hora Infração  \
Ano
2024 0                   NaN           Nenhuma            17
     1                   NaN           Nenhuma            14
     2                   NaN           Nenhuma            14
     3                   NaN           Nenhuma            18
     4                   NaN           Nenhuma            16

       Medição Considerada Excesso Verificado  Qtd Infrações
Ano
2024 0                   0                  0            1.0
     1                   0                  0            1.0
     2                   0                  0            1.0
     3                   0                  0            1.0
     4                   0                  0            1.0

[5 rows x 25 columns]

In [25]:
print('Dimensões:', multas_teste.shape)
print('Níveis do índice:', multas_teste.index.names)
print('Anos:', multas_teste.index.get_level_values('Ano').unique().tolist())

Dimensões: (20000, 25)
Níveis do índice: ['Ano', None]
Anos: [2024, 2025]

In [26]:
del multas_2024_teste
del multas_2025_teste
del multas_teste

In [29]:


arquivo_saida = r'D:\multas_2024_2025_combinadas.csv'

if os.path.exists(arquivo_saida):
    os.remove(arquivo_saida)

# 2024
primeiro_chunk = True

for chunk in pd.read_csv(
    'multas_2024_combinadas.csv',
    sep=';',
    encoding='latin1',
    chunksize=100_000
):
    chunk.insert(0, 'Ano', 2024)

    chunk.to_csv(
        arquivo_saida,
        mode='a',
        index=False,
        sep=';',
        encoding='latin1',
        header=primeiro_chunk
    )

    primeiro_chunk = False

print('2024 concluído.')

# 2025
for chunk in pd.read_csv(
    'multas_2025_combinadas.csv',
    sep=';',
    encoding='latin1',
    chunksize=100_000
):
    chunk.insert(0, 'Ano', 2025)

    chunk.to_csv(
        arquivo_saida,
        mode='a',
        index=False,
        sep=';',
        encoding='latin1',
        header=False
    )

print('2025 concluído.')
print(f'Dataset combinado salvo em: {arquivo_saida}')

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_12916\645273639.py:9: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(

2024 concluído.

OSError: [Errno 28] No space left on device

In [35]:
import shutil
import os

total, usado, livre = shutil.disk_usage("D:")

print(f"Espaço total no D: {total / (1024**3):.2f} GB")
print(f"Espaço usado no D: {usado / (1024**3):.2f} GB")
print(f"Espaço livre no D: {livre / (1024**3):.2f} GB")

arquivo = "D:/multas_2024_2025_combinadas.csv"

if os.path.exists(arquivo):
    tamanho = os.path.getsize(arquivo) / (1024**3)
    print(f"\nArquivo combinado atual: {tamanho:.2f} GB")
else:
    print("\nArquivo combinado ainda não existe.")

Espaço total no D: 14.45 GB
Espaço usado no D: 4.00 GB
Espaço livre no D: 10.45 GB

Arquivo combinado atual: 4.00 GB

In [36]:
# Verificação de valores ausentes nos dados de acidentes

valores_ausentes = acidentes.isna().sum()

print("Quantidade de valores ausentes por variável:")
print(valores_ausentes)

Quantidade de valores ausentes por variável:
id                            0
pesid                         0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                     0
causa_acidente                0
tipo_acidente                 0
classificacao_acidente       10
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                    0
tipo_veiculo              12918
marca                         0
ano_fabricacao_veiculo        0
tipo_envolvido            34342
estado_fisico             34342
idade                         0
sexo                      34342
ilesos                        0
feridos_leves                 0
feridos_graves                0
mortos                        0
latitude                      0
longitude                     0
regional                     17
delegacia                   151
uop                         505
dtype: int64

In [37]:
# Percentual de valores ausentes por variável

percentual_ausentes = (acidentes.isna().mean() * 100).sort_values(ascending=False)

print("Percentual de valores ausentes por variável:")
print(percentual_ausentes)

Percentual de valores ausentes por variável:
sexo                      8.784581
tipo_envolvido            8.784581
estado_fisico             8.784581
tipo_veiculo              3.304386
uop                       0.129177
delegacia                 0.038625
regional                  0.004349
classificacao_acidente    0.002558
latitude                  0.000000
mortos                    0.000000
feridos_graves            0.000000
feridos_leves             0.000000
id_veiculo                0.000000
longitude                 0.000000
idade                     0.000000
ano_fabricacao_veiculo    0.000000
marca                     0.000000
ilesos                    0.000000
id                        0.000000
pesid                     0.000000
tracado_via               0.000000
tipo_pista                0.000000
condicao_metereologica    0.000000
sentido_via               0.000000
fase_dia                  0.000000
tipo_acidente             0.000000
causa_acidente            0.000000
municipio                 0.000000
km                        0.000000
br                        0.000000
uf                        0.000000
horario                   0.000000
dia_semana                0.000000
data_inversa              0.000000
uso_solo                  0.000000
dtype: float64

In [38]:
# Verificação de registros duplicados

duplicados = acidentes.duplicated().sum()

print(f"Quantidade de registros duplicados: {duplicados}")

Quantidade de registros duplicados: 0

### Verificação de registros duplicados

Foi realizada uma verificação de registros duplicados no conjunto de dados de acidentes de 2024 e 2025. O resultado indicou **0 registros duplicados**, portanto não foram identificadas duplicidades exatas entre as 35 variáveis analisadas.

In [39]:
print(acidentes.dtypes)

id                        float64
pesid                       int64
data_inversa               object
dia_semana                 object
horario                    object
uf                         object
br                          int64
km                         object
municipio                  object
causa_acidente             object
tipo_acidente              object
classificacao_acidente     object
fase_dia                   object
sentido_via                object
condicao_metereologica     object
tipo_pista                 object
tracado_via                object
uso_solo                   object
id_veiculo                  int64
tipo_veiculo               object
marca                      object
ano_fabricacao_veiculo      int64
tipo_envolvido             object
estado_fisico              object
idade                       int64
sexo                       object
ilesos                      int64
feridos_leves               int64
feridos_graves              int64
mortos                      int64
latitude                   object
longitude                  object
regional                   object
delegacia                  object
uop                        object
dtype: object

In [40]:
# Conversão da data do acidente para datetime

acidentes['data_inversa'] = pd.to_datetime(
    acidentes['data_inversa'],
    errors='coerce'
)

print(acidentes['data_inversa'].dtype)

datetime64[ns]

In [41]:
print(acidentes['data_inversa'].head())
print(f'\nValores que não puderam ser convertidos: {acidentes["data_inversa"].isna().sum()}')

ano
2024  0   2024-01-01
      1   2024-01-01
      2   2024-01-01
      3   2024-01-01
      4   2024-01-01
Name: data_inversa, dtype: datetime64[ns]

Valores que não puderam ser convertidos: 0

### Conversão da variável `data_inversa`

A variável `data_inversa`, inicialmente armazenada como `object`, foi convertida para o tipo `datetime64[ns]`. A conversão foi realizada sem perdas, pois **nenhum registro apresentou valor inválido ou não convertido**.

In [42]:
print(acidentes['horario'].head(10))
print(f'\nTipo atual: {acidentes["horario"].dtype}')
print(f'Valores ausentes: {acidentes["horario"].isna().sum()}')

ano
2024  0    03:56:00
      1    04:50:00
      2    04:30:00
      3    06:30:00
      4    05:00:00
      5    11:50:00
      6    15:45:00
      7    15:45:00
      8    15:30:00
      9    18:10:00
Name: horario, dtype: object

Tipo atual: object
Valores ausentes: 0

In [43]:
# Conversão da variável horario para datetime

acidentes['horario'] = pd.to_datetime(
    acidentes['horario'],
    format='%H:%M:%S',
    errors='coerce'
)

print(acidentes['horario'].dtype)
print(f'Valores que não puderam ser convertidos: {acidentes["horario"].isna().sum()}')

datetime64[ns]
Valores que não puderam ser convertidos: 0

In [ ]:
# nao gostei, de onde veio esses 1900???
acidentes['horario'].head()

ano
2024  0   1900-01-01 03:56:00
      1   1900-01-01 04:50:00
      2   1900-01-01 04:30:00
      3   1900-01-01 06:30:00
      4   1900-01-01 05:00:00
Name: horario, dtype: datetime64[ns]

In [47]:
# Manter somente o horário, removendo a data artificial de 1900

acidentes['horario'] = acidentes['horario'].dt.time

print(acidentes[['data_inversa', 'horario']].head())
print(f'\nTipo: {acidentes["horario"].dtype}')

       data_inversa   horario
ano
2024 0   2024-01-01  03:56:00
     1   2024-01-01  04:50:00
     2   2024-01-01  04:30:00
     3   2024-01-01  06:30:00
     4   2024-01-01  05:00:00

Tipo: object

### Conversão das variáveis de data e horário

A variável `data_inversa` foi convertida para o tipo `datetime64[ns]`, sem ocorrência de valores inválidos. A variável `horario` foi tratada para manter somente a informação referente ao horário, no formato `HH:MM:SS`, removendo a data artificial adicionada durante a conversão.

In [48]:
print(acidentes['km'].head(10))
print('\nTipo:', acidentes['km'].dtype)
print('\nValores ausentes:', acidentes['km'].isna().sum())

ano
2024  0       38
      1      185
      2      578
      3       18
      4      240
      5      447
      6    852,9
      7    852,9
      8    459,7
      9      550
Name: km, dtype: object

Tipo: object

Valores ausentes: 0

## Erro de iniciante

Esse problema deveria ser resolvido bem antes, na anlise inicial e uso do dicionario. (decimal com virgula)

In [49]:
# Conversão da variável km para tipo numérico

acidentes['km'] = pd.to_numeric(
    acidentes['km'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

print(acidentes[['km']].head(10))
print('\nTipo:', acidentes['km'].dtype)
print('Valores ausentes após conversão:', acidentes['km'].isna().sum())

           km
ano
2024 0   38.0
     1  185.0
     2  578.0
     3   18.0
     4  240.0
     5  447.0
     6  852.9
     7  852.9
     8  459.7
     9  550.0

Tipo: float64
Valores ausentes após conversão: 0

### Conversão da variável `km`

A variável `km` estava armazenada como `object` devido à presença de valores com vírgula como separador decimal. Foi realizada a substituição da vírgula por ponto e, posteriormente, a conversão para o tipo numérico `float64`. A conversão foi concluída sem geração de novos valores ausentes.

In [50]:
print(acidentes[['latitude', 'longitude']].head(10))

print('\nTipos:')
print(acidentes[['latitude', 'longitude']].dtypes)

print('\nValores ausentes:')
print(acidentes[['latitude', 'longitude']].isna().sum())

         latitude  longitude
ano
2024 0  -18.48261  -39.92379
     1  -4.296033 -41.767327
     2 -13.071583 -39.961111
     3 -10.356019 -36.905522
     4 -16.179141 -54.789053
     5  -16.43409 -43.279922
     6 -15.019665 -40.949313
     7 -15.019665 -40.949313
     8 -16.414734 -43.368613
     9 -24.957496 -48.464409

Tipos:
latitude     object
longitude    object
dtype: object

Valores ausentes:
latitude     0
longitude    0
dtype: int64

In [51]:
# Conversão das coordenadas geográficas para tipo numérico

acidentes['latitude'] = pd.to_numeric(
    acidentes['latitude'],
    errors='coerce'
)

acidentes['longitude'] = pd.to_numeric(
    acidentes['longitude'],
    errors='coerce'
)

print(acidentes[['latitude', 'longitude']].head(10))

print('\nTipos:')
print(acidentes[['latitude', 'longitude']].dtypes)

print('\nValores ausentes após conversão:')
print(acidentes[['latitude', 'longitude']].isna().sum())

         latitude  longitude
ano
2024 0 -18.482610 -39.923790
     1  -4.296033 -41.767327
     2 -13.071583 -39.961111
     3 -10.356019 -36.905522
     4 -16.179141 -54.789053
     5 -16.434090 -43.279922
     6 -15.019665 -40.949313
     7 -15.019665 -40.949313
     8 -16.414734 -43.368613
     9 -24.957496 -48.464409

Tipos:
latitude     float64
longitude    float64
dtype: object

Valores ausentes após conversão:
latitude     194529
longitude    194517
dtype: int64

## aqui problema grave, perdemos qualquer valor nam

In [52]:
acidentes_originais_2024 = pd.read_csv(
    'dados_acidentes/acidentes2024.csv',
    sep=';',
    encoding='latin1'
)

acidentes_originais_2025 = pd.read_csv(
    'dados_acidentes/acidentes2025.csv',
    sep=';',
    encoding='latin1'
)

acidentes_originais = pd.concat(
    [acidentes_originais_2024, acidentes_originais_2025],
    keys=[2024, 2025],
    names=['ano']
)

print(acidentes_originais[['latitude', 'longitude']].head())

         latitude  longitude
ano
2024 0  -18.48261  -39.92379
     1  -4.296033 -41.767327
     2 -13.071583 -39.961111
     3 -10.356019 -36.905522
     4 -16.179141 -54.789053

In [53]:
# Verificando valores de latitude e longitude que não são numéricos

latitude_numerica = pd.to_numeric(
    acidentes_originais['latitude'],
    errors='coerce'
)

longitude_numerica = pd.to_numeric(
    acidentes_originais['longitude'],
    errors='coerce'
)

print('Latitude que não pôde ser convertida:')
print(acidentes_originais.loc[
    latitude_numerica.isna(),
    'latitude'
].value_counts().head(20))

print('\nLongitude que não pôde ser convertida:')
print(acidentes_originais.loc[
    longitude_numerica.isna(),
    'longitude'
].value_counts().head(20))

Latitude que não pôde ser convertida:
latitude
-15,17278873    82
-21,688         76
-24,82178987    74
-16,46953       73
-24,92069047    71
-13,386935      71
-12,85966963    69
-7,787595       65
-16,66570005    63
-18,11002       62
-14,39533678    60
-13,985113      59
-18,914454      58
-20,21515       58
-18,891491      58
-5,838956       57
-23,39935369    56
-17,561215      55
-13,88827       55
-23,325237      55
Name: count, dtype: int64

Longitude que não pôde ser convertida:
longitude
-48,39040339    82
-43,451         76
-48,21419034    74
-43,44276       73
-56,09091616    71
-48,25950623    71
-49,10614014    69
-40,215647      65
-43,78533097    63
-41,692162      62
-49,15771114    60
-49,090572      59
-48,639857      58
-42,010512      58
-41,42766       58
-38,559692      57
-46,3004322     56
-40,13967       55
-54,219151      55
-47,827182      55
Name: count, dtype: int64

In [54]:
# Conversão correta de latitude e longitude

acidentes['latitude'] = pd.to_numeric(
    acidentes_originais['latitude'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

acidentes['longitude'] = pd.to_numeric(
    acidentes_originais['longitude'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

print(acidentes[['latitude', 'longitude']].head(10))

print('\nTipos:')
print(acidentes[['latitude', 'longitude']].dtypes)

print('\nValores ausentes após a correção:')
print(acidentes[['latitude', 'longitude']].isna().sum())

         latitude  longitude
ano
2024 0 -18.482610 -39.923790
     1  -4.296033 -41.767327
     2 -13.071583 -39.961111
     3 -10.356019 -36.905522
     4 -16.179141 -54.789053
     5 -16.434090 -43.279922
     6 -15.019665 -40.949313
     7 -15.019665 -40.949313
     8 -16.414734 -43.368613
     9 -24.957496 -48.464409

Tipos:
latitude     float64
longitude    float64
dtype: object

Valores ausentes após a correção:
latitude     0
longitude    0
dtype: int64

In [55]:
del acidentes_originais_2024
del acidentes_originais_2025
del acidentes_originais
del latitude_numerica
del longitude_numerica

In [56]:
# Variáveis que ainda estão como object

colunas_object = acidentes.select_dtypes(include='object').columns

print('Variáveis do tipo object:')
print(colunas_object.tolist())

Variáveis do tipo object:
['dia_semana', 'horario', 'uf', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'tipo_veiculo', 'marca', 'tipo_envolvido', 'estado_fisico', 'sexo', 'regional', 'delegacia', 'uop']

In [57]:
# Conversão das variáveis categóricas para o tipo category

colunas_categoricas = [
    'dia_semana',
    'uf',
    'municipio',
    'causa_acidente',
    'tipo_acidente',
    'classificacao_acidente',
    'fase_dia',
    'sentido_via',
    'condicao_metereologica',
    'tipo_pista',
    'tracado_via',
    'uso_solo',
    'tipo_veiculo',
    'marca',
    'tipo_envolvido',
    'estado_fisico',
    'sexo',
    'regional',
    'delegacia',
    'uop'
]

acidentes[colunas_categoricas] = acidentes[colunas_categoricas].astype('category')

print(acidentes[colunas_categoricas].dtypes)

dia_semana                category
uf                        category
municipio                 category
causa_acidente            category
tipo_acidente             category
classificacao_acidente    category
fase_dia                  category
sentido_via               category
condicao_metereologica    category
tipo_pista                category
tracado_via               category
uso_solo                  category
tipo_veiculo              category
marca                     category
tipo_envolvido            category
estado_fisico             category
sexo                      category
regional                  category
delegacia                 category
uop                       category
dtype: object

In [58]:
acidentes.dtypes

id                               float64
pesid                              int64
data_inversa              datetime64[ns]
dia_semana                      category
horario                           object
uf                              category
br                                 int64
km                               float64
municipio                       category
causa_acidente                  category
tipo_acidente                   category
classificacao_acidente          category
fase_dia                        category
sentido_via                     category
condicao_metereologica          category
tipo_pista                      category
tracado_via                     category
uso_solo                        category
id_veiculo                         int64
tipo_veiculo                    category
marca                           category
ano_fabricacao_veiculo             int64
tipo_envolvido                  category
estado_fisico                   category
idade                              int64
sexo                            category
ilesos                             int64
feridos_leves                      int64
feridos_graves                     int64
mortos                             int64
latitude                         float64
longitude                        float64
regional                        category
delegacia                       category
uop                             category
dtype: object

In [59]:
# Leitura de uma amostra do arquivo combinado de multas

multas_amostra = pd.read_csv(
    'D:/multas_2024_2025_combinadas.csv',
    sep=';',
    encoding='latin1',
    nrows=10000
)

print(multas_amostra.dtypes)

Ano                                int64
Número do Auto                    object
Data da Infração (DD/MM/AAAA)     object
Indicador de Abordagem            object
Assinatura do Auto                object
Sentido Trafego                   object
UF Infração                       object
BR Infração                        int64
Km Infração                        int64
Município                         object
Indicador Veiculo Estrangeiro     object
UF Placa                          object
Descrição Especie Veículo         object
Descrição Marca Veículo           object
Descrição Tipo Veículo            object
Descrição Modelo Veiculo          object
Código da Infração                 int64
Descrição Abreviada Infração      object
Enquadramento da Infração         object
Início Vigência da Infração       object
Fim Vigência Infração            float64
Medição Infração                  object
Hora Infração                      int64
Medição Considerada               object
Excesso Verificado                object
Qtd Infrações                    float64
dtype: object

In [60]:
print(multas_amostra[
    [
        'Data da Infração (DD/MM/AAAA)',
        'Início Vigência da Infração',
        'Fim Vigência Infração'
    ]
].head(10))

  Data da Infração (DD/MM/AAAA) Início Vigência da Infração  \
0                    2024-01-30                  2016-11-01
1                    2024-01-19                  2016-11-01
2                    2024-01-19                  2016-11-01
3                    2024-01-05                  2016-11-01
4                    2024-01-29                  2016-11-01
5                    2024-01-27                  2016-11-01
6                    2024-01-27                  2016-11-01
7                    2024-01-13                  2016-11-01
8                    2024-01-13                  2016-11-01
9                    2024-01-23                  2016-11-01

   Fim Vigência Infração
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
5                    NaN
6                    NaN
7                    NaN
8                    NaN
9                    NaN

In [61]:
print(multas_amostra[
    [
        'Data da Infração (DD/MM/AAAA)',
        'Início Vigência da Infração',
        'Fim Vigência Infração'
    ]
].dtypes)

Data da Infração (DD/MM/AAAA)     object
Início Vigência da Infração       object
Fim Vigência Infração            float64
dtype: object

In [62]:
multas_amostra['Data da Infração (DD/MM/AAAA)'] = pd.to_datetime(
    multas_amostra['Data da Infração (DD/MM/AAAA)'],
    errors='coerce'
)

multas_amostra['Início Vigência da Infração'] = pd.to_datetime(
    multas_amostra['Início Vigência da Infração'],
    errors='coerce'
)

print(multas_amostra[
    [
        'Data da Infração (DD/MM/AAAA)',
        'Início Vigência da Infração'
    ]
].dtypes)

Data da Infração (DD/MM/AAAA)    datetime64[ns]
Início Vigência da Infração      datetime64[ns]
dtype: object

In [63]:
print(multas_amostra['Fim Vigência Infração'].value_counts(dropna=False).head(20))

Fim Vigência Infração
NaN    10000
Name: count, dtype: int64

In [64]:
print(multas_amostra['Hora Infração'].value_counts().head(20))

Hora Infração
11    776
8     742
14    696
13    693
12    672
10    642
15    632
9     620
16    555
7     538
17    495
6     446
18    397
19    312
20    264
21    260
5     255
22    217
4     155
0     146
Name: count, dtype: int64

In [65]:
print('Menor valor:', multas_amostra['Hora Infração'].min())
print('Maior valor:', multas_amostra['Hora Infração'].max())

print('\nValores fora do intervalo 0–23:')
print(
    multas_amostra.loc[
        ~multas_amostra['Hora Infração'].between(0, 23),
        'Hora Infração'
    ].value_counts()
)

Menor valor: 0
Maior valor: 23

Valores fora do intervalo 0–23:
Series([], Name: count, dtype: int64)

In [66]:
multas_amostra['Hora Infração'] = pd.to_timedelta(
    multas_amostra['Hora Infração'],
    unit='h'
)

print(multas_amostra['Hora Infração'].head())
print('\nTipo:')
print(multas_amostra['Hora Infração'].dtype)

0   0 days 17:00:00
1   0 days 14:00:00
2   0 days 14:00:00
3   0 days 18:00:00
4   0 days 16:00:00
Name: Hora Infração, dtype: timedelta64[ns]

Tipo:
timedelta64[ns]

In [67]:
for coluna in [
    'Medição Infração',
    'Medição Considerada',
    'Excesso Verificado'
]:
    print(f'\n--- {coluna} ---') # vai ficar bonito, eu acho
    print(multas_amostra[coluna].value_counts(dropna=False).head(15))

--- Medição Infração ---
Medição Infração
Veiculo       9387
Nenhuma        603
Alcoolemia      10
Name: count, dtype: int64

--- Medição Considerada ---
Medição Considerada
113    716
105    713
101    664
0      608
102    565
111    561
103    531
112    464
104    463
81     333
82     277
114    266
84     226
63     179
64     173
Name: count, dtype: int64

--- Excesso Verificado ---
Excesso Verificado
1     1593
3     1372
2     1292
4     1085
5      994
0      608
10     425
13     346
11     311
7      260
12     235
8      191
6      190
14     180
9      114
Name: count, dtype: int64

In [68]:
for coluna in [
    'Medição Considerada',
    'Excesso Verificado'
]:
    convertido = pd.to_numeric(
        multas_amostra[coluna],
        errors='coerce'
    )

    print(f'\n--- {coluna} ---')
    print('Valores ausentes antes:', multas_amostra[coluna].isna().sum())
    print('Valores que ficariam inválidos:', convertido.isna().sum())

--- Medição Considerada ---
Valores ausentes antes: 0
Valores que ficariam inválidos: 5

--- Excesso Verificado ---
Valores ausentes antes: 0
Valores que ficariam inválidos: 5

In [69]:
for coluna in [
    'Medição Considerada',
    'Excesso Verificado'
]:
    convertido = pd.to_numeric(
        multas_amostra[coluna],
        errors='coerce'
    )

    print(f'\n--- {coluna} ---')
    print(
        multas_amostra.loc[
            convertido.isna(),
            coluna
        ].value_counts(dropna=False)
    )

--- Medição Considerada ---
Medição Considerada
0,52    1
0,07    1
0,64    1
0,04    1
0,06    1
Name: count, dtype: int64

--- Excesso Verificado ---
Excesso Verificado
0,52    1
0,07    1
0,64    1
0,04    1
0,06    1
Name: count, dtype: int64

In [70]:
for coluna in [
    'Medição Considerada',
    'Excesso Verificado'
]:
    multas_amostra[coluna] = pd.to_numeric(
        multas_amostra[coluna]
        .astype(str)
        .str.replace(',', '.', regex=False),
        errors='coerce'
    )

print(multas_amostra[
    [
        'Medição Considerada',
        'Excesso Verificado'
    ]
].dtypes)

Medição Considerada    float64
Excesso Verificado     float64
dtype: object

In [71]:
# Se nao garantir, é porque nao sabe fazer
print(multas_amostra[
    [
        'Medição Considerada',
        'Excesso Verificado'
    ]
].isna().sum())

Medição Considerada    0
Excesso Verificado     0
dtype: int64

In [72]:
multas_amostra['Medição Infração'] = multas_amostra[
    'Medição Infração'
].astype('category')

print(multas_amostra['Medição Infração'].dtype)
print('\nCategorias:')
print(multas_amostra['Medição Infração'].cat.categories)

category

Categorias:
Index(['Alcoolemia', 'Nenhuma', 'Veiculo'], dtype='object')

In [73]:
print(multas_amostra.select_dtypes(include='object').columns.tolist())

['Número do Auto', 'Indicador de Abordagem', 'Assinatura do Auto', 'Sentido Trafego', 'UF Infração', 'Município', 'Indicador Veiculo Estrangeiro', 'UF Placa', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Descrição Tipo Veículo', 'Descrição Modelo Veiculo', 'Descrição Abreviada Infração', 'Enquadramento da Infração']

In [74]:
# Quase tudo aqui, menos o especifico/ individual
colunas_categoricas_multas = [
    'Indicador de Abordagem',
    'Assinatura do Auto',
    'Sentido Trafego',
    'UF Infração',
    'Município',
    'Indicador Veiculo Estrangeiro',
    'UF Placa',
    'Descrição Especie Veículo',
    'Descrição Marca Veículo',
    'Descrição Tipo Veículo',
    'Descrição Modelo Veiculo',
    'Descrição Abreviada Infração',
    'Enquadramento da Infração'
]

multas_amostra[colunas_categoricas_multas] = multas_amostra[
    colunas_categoricas_multas
].astype('category')

print(multas_amostra.dtypes)

Ano                                        int64
Número do Auto                            object
Data da Infração (DD/MM/AAAA)     datetime64[ns]
Indicador de Abordagem                  category
Assinatura do Auto                      category
Sentido Trafego                         category
UF Infração                             category
BR Infração                                int64
Km Infração                                int64
Município                               category
Indicador Veiculo Estrangeiro           category
UF Placa                                category
Descrição Especie Veículo               category
Descrição Marca Veículo                 category
Descrição Tipo Veículo                  category
Descrição Modelo Veiculo                category
Código da Infração                         int64
Descrição Abreviada Infração            category
Enquadramento da Infração               category
Início Vigência da Infração       datetime64[ns]
Fim Vigência Infração                    float64
Medição Infração                        category
Hora Infração                    timedelta64[ns]
Medição Considerada                      float64
Excesso Verificado                       float64
Qtd Infrações                            float64
dtype: object

In [75]:
valores_ausentes_multas = multas_amostra.isna().sum()

print(
    valores_ausentes_multas[
        valores_ausentes_multas > 0
    ].sort_values(ascending=False)
)

Fim Vigência Infração    10000
dtype: int64

In [76]:
duplicados_multas = multas_amostra.duplicated().sum()

print(f'Quantidade de registros duplicados: {duplicados_multas}')

Quantidade de registros duplicados: 0

In [77]:
multas_amostra.dtypes

Ano                                        int64
Número do Auto                            object
Data da Infração (DD/MM/AAAA)     datetime64[ns]
Indicador de Abordagem                  category
Assinatura do Auto                      category
Sentido Trafego                         category
UF Infração                             category
BR Infração                                int64
Km Infração                                int64
Município                               category
Indicador Veiculo Estrangeiro           category
UF Placa                                category
Descrição Especie Veículo               category
Descrição Marca Veículo                 category
Descrição Tipo Veículo                  category
Descrição Modelo Veiculo                category
Código da Infração                         int64
Descrição Abreviada Infração            category
Enquadramento da Infração               category
Início Vigência da Infração       datetime64[ns]
Fim Vigência Infração                    float64
Medição Infração                        category
Hora Infração                    timedelta64[ns]
Medição Considerada                      float64
Excesso Verificado                       float64
Qtd Infrações                            float64
dtype: object

### 3.2 Pré-processamento dos dados de multas

Devido ao grande volume do conjunto de dados de multas, foi utilizada uma **amostra de 10.000 registros** do arquivo combinado para analisar os tipos das variáveis e validar os procedimentos de pré-processamento antes de aplicá-los ao conjunto completo.

Inicialmente, foram verificadas as variáveis relacionadas a datas e horários. A variável `Data da Infração (DD/MM/AAAA)` e a variável `Início Vigência da Infração` foram convertidas para o tipo `datetime64[ns]`.

A variável `Hora Infração` apresentou valores inteiros entre 0 e 23, representando apenas a hora do dia. Dessa forma, foi convertida para o tipo `timedelta64[ns]`, preservando a informação de horário sem adicionar uma data artificial.

As variáveis `Medição Considerada` e `Excesso Verificado` apresentaram valores numéricos e alguns valores decimais registrados com vírgula. Esses valores foram tratados por meio da substituição da vírgula pelo ponto decimal e posteriormente convertidos para o tipo `float64`. Após a conversão, não foram gerados novos valores ausentes nessas variáveis.

A variável `Medição Infração` foi identificada como categórica, apresentando as categorias `Alcoolemia`, `Nenhuma` e `Veiculo`, sendo convertida para o tipo `category`.

As demais variáveis descritivas e de classificação foram analisadas e convertidas para `category`, enquanto `Número do Auto`, por representar um identificador, foi mantido como `object`.

Também foi realizada a verificação de valores ausentes. Na amostra analisada, a única variável que apresentou valores ausentes foi `Fim Vigência Infração`, com 10.000 registros ausentes. Como essa análise foi realizada somente sobre uma amostra, não foi assumido que esse comportamento se repete necessariamente em todo o arquivo.

Por fim, foi realizada a verificação de registros duplicados na amostra, não sendo identificados registros duplicados.

> **Observação:** as conversões e verificações apresentadas nesta etapa foram realizadas sobre uma amostra de 10.000 registros, utilizada para validar os procedimentos de tratamento devido ao grande volume do arquivo completo.

In [78]:
for coluna in [
    'Indicador de Abordagem',
    'Assinatura do Auto',
    'Sentido Trafego',
    'UF Infração',
    'Indicador Veiculo Estrangeiro',
    'UF Placa'
]:
    print(f'\n--- {coluna} ---')
    print(multas_amostra[coluna].value_counts(dropna=False).head(20))

--- Indicador de Abordagem ---
Indicador de Abordagem
S    9670
C     330
Name: count, dtype: int64

--- Assinatura do Auto ---
Assinatura do Auto
N    9981
S      19
Name: count, dtype: int64

--- Sentido Trafego ---
Sentido Trafego
C    5183
D    4817
Name: count, dtype: int64

--- UF Infração ---
UF Infração
RS    9387
MG     328
PR      72
MS      67
PI      55
RN      28
PE      13
TO      13
PB       9
SC       6
PA       5
CE       5
ES       3
SP       3
RO       2
MT       2
RJ       1
SE       1
Name: count, dtype: int64

--- Indicador Veiculo Estrangeiro ---
Indicador Veiculo Estrangeiro
N    8916
S    1084
Name: count, dtype: int64

--- UF Placa ---
UF Placa
RS     7025
'-1    1097
SC      692
MG      432
PR      228
SP      182
MS       60
ES       46
MT       32
RN       25
GO       24
PI       21
DF       20
RJ       20
PB       17
PE       16
BA       13
MA       11
RO       10
CE        9
Name: count, dtype: int64

In [79]:
multas_amostra['Indicador de Abordagem'] = multas_amostra[
    'Indicador de Abordagem'
].map({
    'C': 'Houve abordagem',
    'S': 'Não houve abordagem'
})

multas_amostra['Assinatura do Auto'] = multas_amostra[
    'Assinatura do Auto'
].map({
    'S': 'Sim',
    '': 'Não'
})

multas_amostra['Sentido Trafego'] = multas_amostra[
    'Sentido Trafego'
].map({
    'C': 'Crescente',
    'D': 'Decrescente'
})

multas_amostra['Indicador Veiculo Estrangeiro'] = multas_amostra[
    'Indicador Veiculo Estrangeiro'
].map({
    'S': 'Sim',
    'N': 'Não'
})

In [80]:
for coluna in [
    'Indicador de Abordagem',
    'Assinatura do Auto',
    'Sentido Trafego',
    'Indicador Veiculo Estrangeiro'
]:
    print(f'\n--- {coluna} ---')
    print(multas_amostra[coluna].value_counts(dropna=False))

--- Indicador de Abordagem ---
Indicador de Abordagem
Não houve abordagem    9670
Houve abordagem         330
Name: count, dtype: int64

--- Assinatura do Auto ---
Assinatura do Auto
NaN    9981
Sim      19
Name: count, dtype: int64

--- Sentido Trafego ---
Sentido Trafego
Crescente      5183
Decrescente    4817
Name: count, dtype: int64

--- Indicador Veiculo Estrangeiro ---
Indicador Veiculo Estrangeiro
Não    8916
Sim    1084
Name: count, dtype: int64

In [81]:
print(multas_amostra[
    [
        'Indicador de Abordagem',
        'Assinatura do Auto',
        'Sentido Trafego',
        'Indicador Veiculo Estrangeiro'
    ]
].dtypes)

Indicador de Abordagem           category
Assinatura do Auto                 object
Sentido Trafego                  category
Indicador Veiculo Estrangeiro    category
dtype: object

Voltou para object, maravilha!!

In [82]:
multas_amostra['Assinatura do Auto'] = multas_amostra[
    'Assinatura do Auto'
].astype('category')

print(multas_amostra['Assinatura do Auto'].dtype)
print(multas_amostra['Assinatura do Auto'].value_counts(dropna=False))

category
Assinatura do Auto
NaN    9981
Sim      19
Name: count, dtype: int64

In [83]:
print('UF Infração:')
print(multas_amostra['UF Infração'].value_counts().tail(10))

print('\nUF Placa:')
print(multas_amostra['UF Placa'].value_counts().tail(10))

UF Infração:
UF Infração
PB    9
SC    6
PA    5
CE    5
ES    3
SP    3
RO    2
MT    2
RJ    1
SE    1
Name: count, dtype: int64

UF Placa:
UF Placa
BA    13
MA    11
RO    10
CE     9
PA     7
TO     7
SE     3
AC     1
AM     1
AL     1
Name: count, dtype: int64

In [84]:
for coluna in [
    'Descrição Especie Veículo',
    'Descrição Marca Veículo',
    'Descrição Tipo Veículo',
    'Descrição Modelo Veiculo'
]:
    print(f'\n--- {coluna} ---')
    print(multas_amostra[coluna].value_counts(dropna=False).head(15))

--- Descrição Especie Veículo ---
Descrição Especie Veículo
PASSAGEIRO       5591
MISTO            1425
CARGA            1404
ESPECIAL          853
Não informado     652
TRACAO             75
Name: count, dtype: int64

--- Descrição Marca Veículo ---
Descrição Marca Veículo
Não informado               656
TOYOTA/COROLLA XEI20FLEX     92
VW/GOL 1.0                   70
I/TOYOTA HILUX SWSRXA4FD     40
I/TOYOTA HILUX CD4X4 SRV     39
I/TOYOTA HILUX CDSRXA4FD     37
I/TOYOTA HILUXSW4 SRV4X4     37
VW/24.280 CRM 6X2            36
CHEVROLET/S10 LT DD4A        31
I/TOYOTA HILUX CDSRVA4FD     31
I/VW AMAROK CD 4X4 HIGH      31
CHEV/TRACKER 12T A PR        30
CHEV/TRACKER T A LT          30
REB/REK CL1                  30
FORD/KA FLEX                 29
Name: count, dtype: int64

--- Descrição Tipo Veículo ---
Descrição Tipo Veículo
AUTOMOVEL          5163
CAMINHONETE         966
CAMIONETA           886
Não informado       652
UTILITARIO          540
CAMINHAO            497
REBOQUE             478
SEMI-REBOQUE        294
MOTOCICLETA         279
ONIBUS               99
CAMINHAO TRATOR      76
MOTONETA             40
MICROONIBUS          15
MOTOR-CASA           15
Name: count, dtype: int64

--- Descrição Modelo Veiculo ---
Descrição Modelo Veiculo
Não Informado             1086
COROLLA XEI20FLEX           92
GOL 1.0                     56
REK CL1                     46
TOYOTA HILUX SWSRXA4FD      38
TOYOTA HILUX CD4X4 SRV      37
TOYOTA HILUXSW4 SRV4X4      36
TOYOTA HILUX CDSRXA4FD      34
24.280 CRM 6X2              33
VW AMAROK CD 4X4 HIGH       31
S10 LT DD4A                 30
TRACKER T A LT              30
TRACKER 12T A PR            30
COROLLA XEI18FLEX           29
TOYOTA HILUX CDSRVA4FD      29
Name: count, dtype: int64

Pessoal aqui gosta de Toyota

In [85]:
for coluna in [
    'Descrição Abreviada Infração',
    'Enquadramento da Infração'
]:
    print(f'\n--- {coluna} ---')
    print(multas_amostra[coluna].value_counts(dropna=False).head(20))

--- Descrição Abreviada Infração ---
Descrição Abreviada Infração
Transitar em velocidade superior à máxima permitida em até 20%                                        8458
Transitar em velocidade superior à máxima permitida em mais de 20% até 50%                             897
Desobedecer às ordens emanadas da autorid compet de trânsito ou de seus agentes                        170
Conduzir o veículo registrado que não esteja devidamente licenciado                                     71
Ultrapassar pelo acostamento                                                                            54
Rec sub test,ex clin, peric ou proc q perm cert infl alc/sub. psic for art.277                          38
Transitar em velocidade superior à máxima permitida em mais de 50%                                      32
Dirigir veículo sem possuir CNH/PPD/ACC                                                                 29
Conduzir o veículo em mau estado de conservação, comprometendo a segurança                              28
Deixar o condutor de usar o cinto segurança                                                             17
Ultrapassar pela contramão linha de divisão de fluxos opostos, contínua amarela                         17
Dirigir o veíc usando calçado que ñ se firme nos pés/comprometa utiliz pedais                           12
Conduzir o veículo sem equipamento obrigatório                                                          12
Conduzir o veículo com qualquer uma das placas sem legibilidade e visibilidade                          11
Dirigir sob a influência de álcool                                                                      10
Conduzir o veículo c/ equip do sistema de iluminação e de sinalização alterados                          9
Conduzir o veíc c/ com defeito no sist de iluminação, sinaliz ou lâmpadas queimadas                      9
Dirigir veículo com validade de CNH/PPD vencida há mais de 30 dias                                       9
Conduzir o veículo que não esteja registrado                                                             7
Em mov deix de man aces luz baixa de dia, em rod pis simp sit fora per urb, veíc desp luz rod diur       7
Name: count, dtype: int64

--- Enquadramento da Infração ---
Enquadramento da Infração
218 I        8458
218 II        897
195           170
230 * V        78
202 I          54
165-A          38
218 III        32
162 I          29
230 XVIII      28
167            23
203 V          17
230 IX         14
252 IV         12
230 VI         11
165            10
230 XXII        9
162 V           9
230 XIII        9
244 X           7
250 I e         7
Name: count, dtype: int64

#### Decodificação das variáveis categóricas

Após a conversão dos tipos das variáveis, foi realizada a análise das variáveis categóricas utilizando o dicionário de dados de infrações.

As variáveis `Indicador de Abordagem`, `Assinatura do Auto`, `Sentido Trafego` e `Indicador Veiculo Estrangeiro` possuem códigos que foram interpretados de acordo com as definições apresentadas no dicionário.

Para `Indicador de Abordagem`, os valores `C` e `S` correspondem, respectivamente, a **houve abordagem** e **não houve abordagem**. Para `Sentido Trafego`, `C` representa **crescente** e `D`, **decrescente**. Já `Indicador Veiculo Estrangeiro` utiliza `S` para **sim** e `N` para **não**.

A variável `Assinatura do Auto` utiliza `S` para indicar que o infrator assinou o auto. O dicionário informa que o valor vazio representa a ausência de assinatura. Durante a análise da amostra, foi observada uma diferença entre a documentação e os dados disponibilizados, pois os registros originais apresentaram o valor `N` nessa variável. Por esse motivo, essa ocorrência foi mantida como uma inconsistência a ser registrada, sem atribuir ao código `N` um significado que não esteja documentado na fonte utilizada.

As variáveis `UF Infração` e `UF Placa` já apresentam as siglas das Unidades Federativas, não sendo necessária uma nova codificação.

As variáveis relacionadas às características dos veículos (`Descrição Especie Veículo`, `Descrição Marca Veículo`, `Descrição Tipo Veículo` e `Descrição Modelo Veiculo`) já apresentam informações descritivas, não sendo necessário realizar uma tradução adicional. Da mesma forma, `Descrição Abreviada Infração` e `Enquadramento da Infração` já apresentam a descrição e o enquadramento da infração, respectivamente.

> **Observação:** a análise e as transformações realizadas nesta etapa foram validadas utilizando uma amostra de 10.000 registros devido ao grande volume do conjunto de dados de multas.

In [89]:
for arquivo in arquivo_multas_2024:
    df_auxilio = pd.read_csv(
        arquivo,
        sep=';',
        encoding='latin1',
        usecols=['Data da Infração (DD/MM/AAAA)']
    )

    datas = pd.to_datetime(
        df_auxilio['Data da Infração (DD/MM/AAAA)'],
        errors='coerce'
    )

    junho = (datas.dt.month == 6).sum()

    if junho > 0:
        print(f"{arquivo} → {junho:,} registros de junho")

## é o fim esperado do misterio junho de 2024, nao existe nos registros, ou todos os motoristas, fizeram o que aprenderam na autoescola


Durante a verificação dos arquivos mensais de multas referentes ao ano de 2024, foram identificados 12 arquivos disponíveis. Entretanto, não foi localizado um arquivo denominado `infraçoes2024_06.csv`, correspondente ao mês de junho.

Além disso, os registros referentes a dezembro encontram-se divididos em dois arquivos, `infraçoes2024_12a.csv` e `infraçoes2024_12b.csv`.

Essa característica foi mantida conforme os arquivos disponibilizados pela fonte original, sem a criação ou substituição de dados inexistentes. Portanto, a ausência do arquivo de junho e a divisão de dezembro foram consideradas particularidades da organização dos dados e registradas durante o pré-processamento.

In [94]:
acidentes.to_csv(
    'acidentes_pos_processamento.csv',
    index=True,
    sep=';',
    encoding='utf-8-sig'
)

multas_amostra.to_csv(
    'multas_pos_processamento.csv',
    index=False,
    sep=';',
    encoding='utf-8-sig'
)

print('CSV de acidentes e CSV de multas criados!')

CSV de acidentes e CSV de multas criados!